### ISSUE TITLE
Failed to activate the vibrance-ui package

### ISSUE THREAD

**Issue by tanishqandmac** [silvestreh/ui-theme#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0-nightly6 x64
**Electron**: 6.1.12
**OS**: macOS 11.2
**Thrown From**: [vibrance-ui](https://github.com/silvestreh/ui-theme) package 0.3.0

### Stack Trace

Failed to activate the vibrance-ui package

```
At Cannot read property 'getPrimaryDisplay' of undefined

TypeError: Cannot read property 'getPrimaryDisplay' of undefined
    at Object.init (/packages/vibrance-ui/lib/background-image.js:39:36)
    at Object.activate (/packages/vibrance-ui/lib/main.js:13:21)
    at ThemePackage.activateNow (/private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3546516)
    at /private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:7986
    at ThemePackage.measure (/private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3543506)
    at /private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:7926
    at new Promise (<anonymous>)
    at ThemePackage.activate (/private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:7838)
    at PackageManager.activatePackage (/private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:383597)
    at /private/var/folders/xm/qby166vd2mzdnrshf69trt5m0000gn/T/AppTranslocation/059BB381-1EE9-42B4-8660-0FD439A04D60/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:393133
```

### Commands

```
     -0:36.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.46 
highlight-selected 0.17.0 
vibrance-ui 0.3.0 
zentabs 0.8.9 
```

**Comment by silvestreh** [comment]
Maybe that `electron.screen` object is no longer a thing in a newer version? 🤷 I'll have to look into it

**Comment by vojtech-kasny** [comment]
The same issue here

```
Cannot read property 'getPrimaryDisplay' of undefined
Hide Stack Trace
TypeError: Cannot read property 'getPrimaryDisplay' of undefined
    at Object.init (file:///C:/Users/<username>/.atom/packages/vibrance-ui/lib/background-image.js:39:36)
    at Object.activate (file:///C:/Users/<username>/.atom/packages/vibrance-ui/lib/main.js:13:21)
    at ThemePackage.activateNow (C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3658881)
    at C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:7986
    at ThemePackage.measure (C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3655871)
    at C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:7926
    at new Promise (<anonymous>)
    at ThemePackage.activate (C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:7838)
    at PackageManager.activatePackage (C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:383646)
    at C:\Users\<username>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:393182
```
